### PR TITLE
Changed version of pure api to 523

### PR DESCRIPTION
**Pull request by ajkiessl**
I'm going to deploy this branch to QA and run the entire Pure import to make sure it's working properly.  I'll merge and deploy on Monday if all goes well.

### CODE REVIEW

**Review by banukutlu — APPROVED** [review]
looks good to me ✔️  🤞🏻 hope it all goes fine with the importer then we can 🚢

**Review by Smullz622 — APPROVED** [review]
Looks good to me

**Comment by ajkiessl** [comment]
I'm actually going to run this on stage.

**Comment by ajkiessl** [comment]
closes #535

**Pull request merged**
